### ISSUE TITLE
Zooniverse ideal metadata

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildRecordsData#106]
I think we should define all the metadata that we need to keep track of in the first place, regardless of what has been done so far. What do you think of the following columns ? (One line for each chunk)

- index
- recording
- onset (of the 500 ms chunk)
- offset (of the 500 ms chunk)
- segment_onset (of the n*500 ms padded segment the chunk belongs to)
- segment_offset (of the n*500 ms padded segment the chunk belongs to)
- wav (relative path to the chunk wav export)
- mp3 (relative path to the chunk mp3 export)
- speaker_type (which speaker_type was targetted)
- date_extracted
- uploaded (boolean indicating whether the chunk has already been uploaded to Zooniverse)
- ~~project_slug (zooniverse project slug)~~ I think it should be replaced with the id
- project_id (zooniverse project id)
- subject_set (zooniverse subject set)
- batch (batch number of the chunk)
- zooniverse_id (zooniverse subject id, unique per chunk. This is what allows to later merge the classifications with the metadata)

@alecristia what do you think ?

**Comment by alecristia** [comment]
great initiative.

### Segment level metadata

Right now we only have one project, but we will soon have 3 active ones, so we should say which. That is project_id, right?

For Marvin's project we'll exhaustively sample without filtering by speaker (so that it's algorithm-independent). So perhaps speaker_type could be segment_type.

Another field would be a keyword that needs to be defined elsewhere, perhaps in an extraction metadata, which explains what was the logic and procedure for extraction, including whether LENA or VTC was used (in fact, more generally, what annotation it was based on), how many segments, of which speaker types, or whether it was exhaustive sampling -- in which case, how many sections & of what length. So we can only put in a keyword (which may be something like marvin-202101) in the metadata, but somewhere we'll spell out all of those details. Or should that be in a yaml file that is used to define the data extraction routine? --> I'm proposing a process-level metadata next

### Process-level metadata

(which spells out what the keyword in segment-level metadata is)

Regarding that, we are now considering an alternative form of extraction, whereby after segments are identified, these are fed to an automated syllabifier, which then outputs estimated syllable boundaries, which are then padded up to 500ms. The hope is to avoid chunks that have the end of one syllable and the beginning of the next. This will only be used in a later task, where people transcribe the sounds babies make, and not for the current one (where the transition between syllables is precisely what helps them distinguish canonical from non-canonical). This could be in the data extraction routine eventually, but it won't be ready for months. This info would not go in a segment-level metadata, but could appear somewhere (in a process-level metadata).

And another direction that is less certain is how to deal with crying, which is confused with non-canonical too much. We're not sure but we may also try to apply classifiers to filter out crying based on longer stretches than 500ms. This info would not go in a segment-level metadata, but could appear somewhere (in a process-level metadata).

### Recording-level metadata

We are assuming this is recordings.csv & children.csv, right? So we don't need to spell them out.

**Comment by lucasgautheron** [comment]
I like the idea of storing all the parameters of the run somewhere
---

> This info would not go in a segment-level metadata, but could appear somewhere (in a process-level metadata).
For that we can have a tags column
---

> We are assuming this is recordings.csv & children.csv, right? So we don't need to spell them out.
yes

**Comment by lucasgautheron** [comment]
These are the run parameters that I've got so far:

```python
parameters = [
            ['export_id', id],
            ['version', ChildProject.__version__],
            ['date_extracted', datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
            ['speaker_type', ','.join(target_speaker_type)],
            ['sample_size', sample_size],
            ['chunk_length', chunk_length],
            ['annotation_set', annotation_set]
        ]
```

(export_id would be something like marvin-202101)

**Comment by lucasgautheron** [comment]
Something else we should decide how to deal with : segments ID
Why were they introduced in the first place ?

The triplet `(recording, segment_onset, segment_offset)` unequivocally defines a segment. Isn't it enough ?
In which case, do you agree that the values of `segment_onset` and `segment_offset` should be the padded values for the whole segment ? (so that `segment_offset-segment_onset` should be a multiple of 500 ms)

The case for using the padded values would be:

 - The padded values are closer to what has actually been classified by the contributors
 - The padding algorithm might change. Therefore, its input by itself does not yield reliable information about its output.
 - In any case, using the output values, one can still try to match them with whatever annotations were used in the first place to target the segment.

So I wonder if we shouldn't get rid of SegmentId at all... What do you think @alecristia ?

**Comment by lucasgautheron** [comment]
`--algorithm: random,high_volubility`

 random:
    --sample_size
    --speaker_type

  high_volubility:
    --speaker_type
    --windows_length
    --windows_amount
