### ISSUE TITLE
Annotation and segments manipulation wishlist

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildRecordsData#38]
I suggest that we discuss here a list of functions that could help manipulating annotations and segments more easily. Here is what I suggest, please add any : 

- `get_segments(annotations)`: returns segments corresponding to a list of annotations, as one single merged dataframe.
`annotations`: a dataframe containing the annotations for which the segments should be retrieved.

- `intersection(a, b)`: compute the intersection of two sets of annotations
`a`: a dataframe containing annotations as in the meta data, e.g. : 
```
set,recording_filename,time_seek,raw_filename,range_onset,range_offset,format
textgrid,sound.wav,3600,example.TextGrid,200,320,TextGrid
textgrid,sound.wav,7200,example.TextGrid,200,320,TextGrid
```
`b`: a dataframe containing annotations as in the meta data, e.g.:
```
set,recording_filename,time_seek,raw_filename,range_onset,range_offset,format
vtc_rttm,sound.wav,0,example.rttm,0,7500,vtc_rttm
```
Returns : 
a tuple of two dataframes, e.g.: 
```
annotation_filename,format,range_offset,range_onset,raw_filename,recording_filename,set,time_seek
textgrid/sound_3600.csv,TextGrid,320,200,example.TextGrid,sound.wav,textgrid,3600
textgrid/sound_7200.csv,TextGrid,300,200,example.TextGrid,sound.wav,textgrid,7200
```
and 
```
annotation_filename,format,range_offset,range_onset,raw_filename,recording_filename,set,time_seek
vtc_rttm/sound_0.csv,vtc_rttm,3920,3800,example.rttm,sound.wav,vtc_rttm,0
vtc_rttm/sound_0.csv,vtc_rttm,7500,7400,example.rttm,sound.wav,vtc_rttm,0
```

- `clip(segments, start, stop)`: clip every interval in `segments` from `start` to `stop`, dropping segments that are out of bounds.

- `fill_silences(segments, silence_speaker_type = 'SIL')`: populate the dataframe segments with intervals for every silence, setting `silence_speaker_type` as the speaker_type for these intervals

**Comment by lucasgautheron** [comment]
Feel free to suggest more @alecristia

**Comment by alecristia** [comment]
Hmm I'm not sure I follow the logic of these. What would be the goal? Some of these are for me things that must be done to correct errors:

- clip(segments, start, stop): clip every interval in segments from start to stop, dropping segments that are out of bounds. <-- I can only imagine wanting to do that because human annotators sometimes incorrectly start/stop segments

- fill_silences(segments, silence_speaker_type = 'SIL'): populate the dataframe segments with intervals for every silence, setting silence_speaker_type as the speaker_type for these intervals <-- is the idea of this that sections that were supposed to be annotated, when they have no segments, we need to infer that this is silence? Then shouldn't this be done automatically (ie as part of the annotation cleaning)?

The other function is something that I do at the analysis - I'll explain

**Comment by alecristia** [comment]
sorry, i was interrupted -- "intersection(a, b)" is what I typically do in R, with left_join or merge. We don't need to rewrite this function in a different package. Typically this is at the analysis stage, when you decide which metadata you need and how you want to integrate it.

Does that make sense, or am I perhaps misunderstanding what we are trying to do here?

**Comment by lucasgautheron** [comment]
+ select portions of audio to annotate based on a set of critieria
